name: EpicClans
version: 1.0.0-ALPHA
main: me.Vark123.EpicClans.Main
author: Vark123
depend: [CalendarEvents,MythicMobs,NBTAPI,WorldGuard,EpicRPG,EpicRPGSkillsAndQuests,PlaceholderAPI]
api-version: 1.18

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.3

commands:
  epicclan:
    aliases: [klan, clan]