package me.Vark123.EpicClans.ClanSystem;

public enum ClanPermission {

	INVITE,				//ZAPRASZANIE GRACZY
	KICK,				//WYRZUCANIE GRACZY
	LOG,				//DOSTEP DO PODGLADU LOGOW ZDARZEN
	TOURNAMENT,			//ZAPISYWANIE KLANU NA TURNIEJE
	UPGRADE,			//ULEPSZANIE KLANU
	BACKPACK,			//PLECAK KLANOWY
	PARTY,				//DOSTEP DO KOMENDY /klan party
	SHOP,				//DOSTEP DO SKLEPU KLANOWEGO
	PROMOTE,			//ZARZADZANIE RANGAMI UCZESTNIKOW Z WYZSZYM PRIORYTEM
	LEADER,				//MOZLIWOSC USUWANIA KLANU I ZMIANY LIDERA ORAZ TWORZENIA ROL
	
}
